module.exports = async (client, guild) => {
  const Discord = require("discord.js")
let invitechannels = guild.channels.cache.filter(c=> c.permissionsFor(guild.me).has('CREATE_INSTANT_INVITE'))
let canal = client.channels.resolve("710256135046692924")
let canal2 = guild.channels.cache.filter(x => x.type === "text").random()
canal2.send(new Discord.MessageEmbed()
.setDescription("Muchas gracias por meterme a tu Servidor!, puedes ver todos mis comandos con el comando `_comandos`, o te puedes unir al [Servidor de Soporte!](https://discord.gg/QQ74VGN)")
.setColor("RANDOM"))

if(!guild.me.hasPermission("ADMINISTRATOR")) return canal.send(new Discord.MessageEmbed()
.setTitle("Me han agregado a un servidor")
.addField("Miembros:", guild.memberCount, true)
.addField("Nombre:", guild.name, true)
.addField("ID:", guild.id, true)
.setThumbnail(guild.iconURL())
.addField("Owner:", guild.owner.user.tag, true)
.addField("Invite:", "No tenemos invitación", true)
.addField("Ahora tenemos:", client.guilds.cache.size.toLocaleString()+" servidores!", true)
.setColor("#5b00ff"))

invitechannels.random().createInvite().then(invite=> canal.send(new Discord.MessageEmbed()
.setTitle("Me han agregado a un servidor")
.addField("Miembros:", guild.memberCount, true)
.addField("Nombre:", guild.name, true)
.addField("ID:", guild.id, true)
.setThumbnail(guild.iconURL())
.addField("Owner:", guild.owner.user.tag, true)
.addField("Invite:", "[Invitación](https://discord.gg/"+invite.code+")", true)
.addField("Ahora tenemos:", client.guilds.cache.size.toLocaleString()+" servidores!", true)
.setColor("#5b00ff"))) 
}